Import('*')

rotn_src = ([
    'rotn_encrypt.c'])

if GetOption("enable_static"):
    rotn_encrypt = env.StaticLibrary(target="rotn", source=rotn_src)
else:   
    rotn_encrypt = env.SharedLibrary(target="rotn", source=rotn_src)
