/* DO NOT EDIT: THIS FILE IS AUTOMATICALLY GENERATED BY log_auto-test-gen.sh */

#pragma GCC diagnostic error "-Wno-used-but-marked-unused"
#pragma clang diagnostic ignored "-Wused-but-marked-unused"

#include "log_auto_fmt.h"
#include "log_auto_direct.h"

#define testutil_assertfmt__(a, fmt, ...)                                                         \
    do {                                                                                          \
        if (!(a))                                                                                 \
            testutil_die(0, "\n%s:%d:\n  %s:\n    " fmt, __FILE__, __LINE__, __PRETTY_FUNCTION__, \
              __VA_ARGS__);                                                                       \
    } while (0)

#define assert_eq(a, b) testutil_assertfmt__((a) == (b), "%s != %s", #a, #b)
#define assert_eq_uint16_t(a, b) \
    testutil_assertfmt__((a) == (b), "%s != %s : (%u) != (%u)", #a, #b, (a), (b))
#define assert_eq_uint32_t(a, b) \
    testutil_assertfmt__((a) == (b), "%s != %s : (%lu) != (%lu)", #a, #b, (a), (b))
#define assert_eq_uint64_t(a, b) \
    testutil_assertfmt__((a) == (b), "%s != %s : (%llu) != (%llu)", #a, #b, (a), (b))

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_col_modify(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, uint64_t recno, WT_ITEM *value)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    uint64_t recno_fmt, recno_direct;
    WT_ITEM value_fmt, value_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    recno_fmt = recno;
    recno_direct = recno;
    value_fmt.data = value->data;
    value_direct.data = value->data;
    value_fmt.size = value->size;
    value_direct.size = value->size;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(
      __wt_logop_col_modify_pack__fmt(session, logrec_fmt, fileid_fmt, recno_fmt, &value_fmt) == 0);
    assert(__wt_logop_col_modify_pack__direct(
             session, logrec_direct, fileid_direct, recno_direct, &value_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_col_modify_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &fileid_fmt, &recno_fmt, &value_fmt) == 0);
    assert(__wt_logop_col_modify_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &recno_direct, &value_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert(recno_fmt == recno_direct);
    assert_eq_uint64_t(value_fmt.size, value_direct.size);
    assert(memcmp(value_fmt.data, value_direct.data, value_fmt.size) == 0);

    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_col_put(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, uint64_t recno, WT_ITEM *value)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    uint64_t recno_fmt, recno_direct;
    WT_ITEM value_fmt, value_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    recno_fmt = recno;
    recno_direct = recno;
    value_fmt.data = value->data;
    value_direct.data = value->data;
    value_fmt.size = value->size;
    value_direct.size = value->size;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(
      __wt_logop_col_put_pack__fmt(session, logrec_fmt, fileid_fmt, recno_fmt, &value_fmt) == 0);
    assert(__wt_logop_col_put_pack__direct(
             session, logrec_direct, fileid_direct, recno_direct, &value_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_col_put_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &fileid_fmt, &recno_fmt, &value_fmt) == 0);
    assert(__wt_logop_col_put_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &recno_direct, &value_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert(recno_fmt == recno_direct);
    assert_eq_uint64_t(value_fmt.size, value_direct.size);
    assert(memcmp(value_fmt.data, value_direct.data, value_fmt.size) == 0);

    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_col_remove(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, uint64_t recno)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    uint64_t recno_fmt, recno_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    recno_fmt = recno;
    recno_direct = recno;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(__wt_logop_col_remove_pack__fmt(session, logrec_fmt, fileid_fmt, recno_fmt) == 0);
    assert(
      __wt_logop_col_remove_pack__direct(session, logrec_direct, fileid_direct, recno_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_col_remove_unpack__fmt(
             session, &data_fmt, data_fmt + logrec_fmt->size, &fileid_fmt, &recno_fmt) == 0);
    assert(__wt_logop_col_remove_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &recno_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert(recno_fmt == recno_direct);
    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_col_truncate(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, uint64_t start, uint64_t stop)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    uint64_t start_fmt, start_direct;
    uint64_t stop_fmt, stop_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    start_fmt = start;
    start_direct = start;
    stop_fmt = stop;
    stop_direct = stop;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(
      __wt_logop_col_truncate_pack__fmt(session, logrec_fmt, fileid_fmt, start_fmt, stop_fmt) == 0);
    assert(__wt_logop_col_truncate_pack__direct(
             session, logrec_direct, fileid_direct, start_direct, stop_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_col_truncate_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &fileid_fmt, &start_fmt, &stop_fmt) == 0);
    assert(__wt_logop_col_truncate_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &start_direct, &stop_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert(start_fmt == start_direct);
    assert(stop_fmt == stop_direct);
    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_row_modify(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, WT_ITEM *key, WT_ITEM *value)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    WT_ITEM key_fmt, key_direct;
    WT_ITEM value_fmt, value_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    key_fmt.data = key->data;
    key_direct.data = key->data;
    key_fmt.size = key->size;
    key_direct.size = key->size;
    value_fmt.data = value->data;
    value_direct.data = value->data;
    value_fmt.size = value->size;
    value_direct.size = value->size;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(
      __wt_logop_row_modify_pack__fmt(session, logrec_fmt, fileid_fmt, &key_fmt, &value_fmt) == 0);
    assert(__wt_logop_row_modify_pack__direct(
             session, logrec_direct, fileid_direct, &key_direct, &value_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_row_modify_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &fileid_fmt, &key_fmt, &value_fmt) == 0);
    assert(__wt_logop_row_modify_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &key_direct, &value_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert_eq_uint64_t(key_fmt.size, key_direct.size);
    assert(memcmp(key_fmt.data, key_direct.data, key_fmt.size) == 0);

    assert_eq_uint64_t(value_fmt.size, value_direct.size);
    assert(memcmp(value_fmt.data, value_direct.data, value_fmt.size) == 0);

    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_row_put(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, WT_ITEM *key, WT_ITEM *value)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    WT_ITEM key_fmt, key_direct;
    WT_ITEM value_fmt, value_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    key_fmt.data = key->data;
    key_direct.data = key->data;
    key_fmt.size = key->size;
    key_direct.size = key->size;
    value_fmt.data = value->data;
    value_direct.data = value->data;
    value_fmt.size = value->size;
    value_direct.size = value->size;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(
      __wt_logop_row_put_pack__fmt(session, logrec_fmt, fileid_fmt, &key_fmt, &value_fmt) == 0);
    assert(__wt_logop_row_put_pack__direct(
             session, logrec_direct, fileid_direct, &key_direct, &value_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_row_put_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &fileid_fmt, &key_fmt, &value_fmt) == 0);
    assert(__wt_logop_row_put_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &key_direct, &value_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert_eq_uint64_t(key_fmt.size, key_direct.size);
    assert(memcmp(key_fmt.data, key_direct.data, key_fmt.size) == 0);

    assert_eq_uint64_t(value_fmt.size, value_direct.size);
    assert(memcmp(value_fmt.data, value_direct.data, value_fmt.size) == 0);

    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_row_remove(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, WT_ITEM *key)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    WT_ITEM key_fmt, key_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    key_fmt.data = key->data;
    key_direct.data = key->data;
    key_fmt.size = key->size;
    key_direct.size = key->size;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(__wt_logop_row_remove_pack__fmt(session, logrec_fmt, fileid_fmt, &key_fmt) == 0);
    assert(
      __wt_logop_row_remove_pack__direct(session, logrec_direct, fileid_direct, &key_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_row_remove_unpack__fmt(
             session, &data_fmt, data_fmt + logrec_fmt->size, &fileid_fmt, &key_fmt) == 0);
    assert(__wt_logop_row_remove_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &key_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert_eq_uint64_t(key_fmt.size, key_direct.size);
    assert(memcmp(key_fmt.data, key_direct.data, key_fmt.size) == 0);

    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_row_truncate(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t fileid, WT_ITEM *start, WT_ITEM *stop, uint32_t mode)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t fileid_fmt, fileid_direct;
    WT_ITEM start_fmt, start_direct;
    WT_ITEM stop_fmt, stop_direct;
    uint32_t mode_fmt, mode_direct;

    fileid_fmt = fileid;
    fileid_direct = fileid;
    start_fmt.data = start->data;
    start_direct.data = start->data;
    start_fmt.size = start->size;
    start_direct.size = start->size;
    stop_fmt.data = stop->data;
    stop_direct.data = stop->data;
    stop_fmt.size = stop->size;
    stop_direct.size = stop->size;
    mode_fmt = mode;
    mode_direct = mode;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(__wt_logop_row_truncate_pack__fmt(
             session, logrec_fmt, fileid_fmt, &start_fmt, &stop_fmt, mode_fmt) == 0);
    assert(__wt_logop_row_truncate_pack__direct(
             session, logrec_direct, fileid_direct, &start_direct, &stop_direct, mode_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_row_truncate_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &fileid_fmt, &start_fmt, &stop_fmt, &mode_fmt) == 0);
    assert(__wt_logop_row_truncate_unpack__direct(session, &data_direct,
             data_direct + logrec_direct->size, &fileid_direct, &start_direct, &stop_direct,
             &mode_direct) == 0);

    assert(fileid_fmt == fileid_direct);
    assert_eq_uint64_t(start_fmt.size, start_direct.size);
    assert(memcmp(start_fmt.data, start_direct.data, start_fmt.size) == 0);

    assert_eq_uint64_t(stop_fmt.size, stop_direct.size);
    assert(memcmp(stop_fmt.data, stop_direct.data, stop_fmt.size) == 0);

    assert(mode_fmt == mode_direct);
    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_checkpoint_start(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/

    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(__wt_logop_checkpoint_start_pack__fmt(session, logrec_fmt) == 0);
    assert(__wt_logop_checkpoint_start_pack__direct(session, logrec_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_checkpoint_start_unpack__fmt(
             session, &data_fmt, data_fmt + logrec_fmt->size) == 0);
    assert(__wt_logop_checkpoint_start_unpack__direct(
             session, &data_direct, data_direct + logrec_direct->size) == 0);

    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_prev_lsn(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct, WT_LSN *prev_lsn)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    WT_LSN prev_lsn_fmt, prev_lsn_direct;

    prev_lsn_fmt.l.file = prev_lsn->l.file;
    prev_lsn_direct.l.file = prev_lsn->l.file;
    prev_lsn_fmt.l.offset = prev_lsn->l.offset;
    prev_lsn_direct.l.offset = prev_lsn->l.offset;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(__wt_logop_prev_lsn_pack__fmt(session, logrec_fmt, &prev_lsn_fmt) == 0);
    assert(__wt_logop_prev_lsn_pack__direct(session, logrec_direct, &prev_lsn_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_prev_lsn_unpack__fmt(
             session, &data_fmt, data_fmt + logrec_fmt->size, &prev_lsn_fmt) == 0);
    assert(__wt_logop_prev_lsn_unpack__direct(
             session, &data_direct, data_direct + logrec_direct->size, &prev_lsn_direct) == 0);

    assert(prev_lsn_fmt.l.file == prev_lsn_direct.l.file);
    assert(prev_lsn_fmt.l.offset == prev_lsn_direct.l.offset);

    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_backup_id(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint32_t index, uint64_t granularity, const char *id)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint32_t index_fmt, index_direct;
    uint64_t granularity_fmt, granularity_direct;
    const char *id_fmt, *id_direct;

    index_fmt = index;
    index_direct = index;
    granularity_fmt = granularity;
    granularity_direct = granularity;
    id_fmt = id;
    id_direct = id;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(
      __wt_logop_backup_id_pack__fmt(session, logrec_fmt, index_fmt, granularity_fmt, id_fmt) == 0);
    assert(__wt_logop_backup_id_pack__direct(
             session, logrec_direct, index_direct, granularity_direct, id_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_backup_id_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &index_fmt, &granularity_fmt, &id_fmt) == 0);
    assert(
      __wt_logop_backup_id_unpack__direct(session, &data_direct, data_direct + logrec_direct->size,
        &index_direct, &granularity_direct, &id_direct) == 0);

    assert(index_fmt == index_direct);
    assert(granularity_fmt == granularity_direct);
    assert(!strcmp(id_fmt, id_direct));
    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_one__wt_logop_txn_timestamp(WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt,
  WT_ITEM *logrec_direct, uint64_t time_sec, uint64_t time_nsec, uint64_t commit_ts,
  uint64_t durable_ts, uint64_t first_commit_ts, uint64_t prepare_ts, uint64_t read_ts)
{
    const uint8_t *data_fmt, *data_direct;
    /*size_t sz_fmt, sz_direct;*/
    uint64_t time_sec_fmt, time_sec_direct;
    uint64_t time_nsec_fmt, time_nsec_direct;
    uint64_t commit_ts_fmt, commit_ts_direct;
    uint64_t durable_ts_fmt, durable_ts_direct;
    uint64_t first_commit_ts_fmt, first_commit_ts_direct;
    uint64_t prepare_ts_fmt, prepare_ts_direct;
    uint64_t read_ts_fmt, read_ts_direct;

    time_sec_fmt = time_sec;
    time_sec_direct = time_sec;
    time_nsec_fmt = time_nsec;
    time_nsec_direct = time_nsec;
    commit_ts_fmt = commit_ts;
    commit_ts_direct = commit_ts;
    durable_ts_fmt = durable_ts;
    durable_ts_direct = durable_ts;
    first_commit_ts_fmt = first_commit_ts;
    first_commit_ts_direct = first_commit_ts;
    prepare_ts_fmt = prepare_ts;
    prepare_ts_direct = prepare_ts;
    read_ts_fmt = read_ts;
    read_ts_direct = read_ts;
    logrec_fmt->size = logrec_direct->size = 0;
    /*sz_fmt = logrec_fmt->size;*/
    /*sz_direct = logrec_direct->size;*/

    /* test packing */
    assert(__wt_logop_txn_timestamp_pack__fmt(session, logrec_fmt, time_sec_fmt, time_nsec_fmt,
             commit_ts_fmt, durable_ts_fmt, first_commit_ts_fmt, prepare_ts_fmt, read_ts_fmt) == 0);
    assert(__wt_logop_txn_timestamp_pack__direct(session, logrec_direct, time_sec_direct,
             time_nsec_direct, commit_ts_direct, durable_ts_direct, first_commit_ts_direct,
             prepare_ts_direct, read_ts_direct) == 0);

    assert(logrec_fmt->size == logrec_direct->size);
    assert(memcmp(logrec_fmt->data, logrec_direct->data, logrec_fmt->size) == 0);

    /* test unpacking */
    data_fmt = logrec_fmt->data;
    data_direct = logrec_direct->data;
    assert(__wt_logop_txn_timestamp_unpack__fmt(session, &data_fmt, data_fmt + logrec_fmt->size,
             &time_sec_fmt, &time_nsec_fmt, &commit_ts_fmt, &durable_ts_fmt, &first_commit_ts_fmt,
             &prepare_ts_fmt, &read_ts_fmt) == 0);
    assert(
      __wt_logop_txn_timestamp_unpack__direct(session, &data_direct,
        data_direct + logrec_direct->size, &time_sec_direct, &time_nsec_direct, &commit_ts_direct,
        &durable_ts_direct, &first_commit_ts_direct, &prepare_ts_direct, &read_ts_direct) == 0);

    assert(time_sec_fmt == time_sec_direct);
    assert(time_nsec_fmt == time_nsec_direct);
    assert(commit_ts_fmt == commit_ts_direct);
    assert(durable_ts_fmt == durable_ts_direct);
    assert(first_commit_ts_fmt == first_commit_ts_direct);
    assert(prepare_ts_fmt == prepare_ts_direct);
    assert(read_ts_fmt == read_ts_direct);
    /*logrec_fmt->size = sz_fmt;*/
    /*logrec_direct->size = sz_direct;*/
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_col_modify(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    uint64_t recno;
    WT_ITEM value;

    fileid = (uint32_t)(0);
    recno = (uint64_t)(0);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(1);
    recno = (uint64_t)(1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    recno = (uint64_t)(POS_1BYTE_MAX - 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    recno = (uint64_t)(POS_1BYTE_MAX);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    recno = (uint64_t)(POS_1BYTE_MAX + 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    recno = (uint64_t)(POS_2BYTE_MAX - 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    recno = (uint64_t)(POS_2BYTE_MAX);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    recno = (uint64_t)(POS_2BYTE_MAX + 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(rand());
    recno = (uint64_t)(rand());
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(rand());
    recno = (uint64_t)(rand());
    value.data = "data";
    value.size = 4;
    test_cmp_one__wt_logop_col_modify(session, logrec_fmt, logrec_direct, fileid, recno, &value);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_col_put(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    uint64_t recno;
    WT_ITEM value;

    fileid = (uint32_t)(0);
    recno = (uint64_t)(0);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(1);
    recno = (uint64_t)(1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    recno = (uint64_t)(POS_1BYTE_MAX - 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    recno = (uint64_t)(POS_1BYTE_MAX);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    recno = (uint64_t)(POS_1BYTE_MAX + 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    recno = (uint64_t)(POS_2BYTE_MAX - 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    recno = (uint64_t)(POS_2BYTE_MAX);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    recno = (uint64_t)(POS_2BYTE_MAX + 1);
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(rand());
    recno = (uint64_t)(rand());
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);

    fileid = (uint32_t)(rand());
    recno = (uint64_t)(rand());
    value.data = "data";
    value.size = 4;
    test_cmp_one__wt_logop_col_put(session, logrec_fmt, logrec_direct, fileid, recno, &value);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_col_remove(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    uint64_t recno;

    fileid = (uint32_t)(0);
    recno = (uint64_t)(0);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(1);
    recno = (uint64_t)(1);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    recno = (uint64_t)(POS_1BYTE_MAX - 1);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    recno = (uint64_t)(POS_1BYTE_MAX);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    recno = (uint64_t)(POS_1BYTE_MAX + 1);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    recno = (uint64_t)(POS_2BYTE_MAX - 1);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    recno = (uint64_t)(POS_2BYTE_MAX);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    recno = (uint64_t)(POS_2BYTE_MAX + 1);
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(rand());
    recno = (uint64_t)(rand());
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);

    fileid = (uint32_t)(rand());
    recno = (uint64_t)(rand());
    test_cmp_one__wt_logop_col_remove(session, logrec_fmt, logrec_direct, fileid, recno);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_col_truncate(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    uint64_t start;
    uint64_t stop;

    fileid = (uint32_t)(0);
    start = (uint64_t)(0);
    stop = (uint64_t)(0);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(1);
    start = (uint64_t)(1);
    stop = (uint64_t)(1);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    start = (uint64_t)(POS_1BYTE_MAX - 1);
    stop = (uint64_t)(POS_1BYTE_MAX - 1);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    start = (uint64_t)(POS_1BYTE_MAX);
    stop = (uint64_t)(POS_1BYTE_MAX);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    start = (uint64_t)(POS_1BYTE_MAX + 1);
    stop = (uint64_t)(POS_1BYTE_MAX + 1);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    start = (uint64_t)(POS_2BYTE_MAX - 1);
    stop = (uint64_t)(POS_2BYTE_MAX - 1);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    start = (uint64_t)(POS_2BYTE_MAX);
    stop = (uint64_t)(POS_2BYTE_MAX);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    start = (uint64_t)(POS_2BYTE_MAX + 1);
    stop = (uint64_t)(POS_2BYTE_MAX + 1);
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(rand());
    start = (uint64_t)(rand());
    stop = (uint64_t)(rand());
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);

    fileid = (uint32_t)(rand());
    start = (uint64_t)(rand());
    stop = (uint64_t)(rand());
    test_cmp_one__wt_logop_col_truncate(session, logrec_fmt, logrec_direct, fileid, start, stop);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_row_modify(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    WT_ITEM key;
    WT_ITEM value;

    fileid = (uint32_t)(0);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(rand());
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(rand());
    key.data = "data";
    key.size = 4;
    value.data = "data";
    value.size = 4;
    test_cmp_one__wt_logop_row_modify(session, logrec_fmt, logrec_direct, fileid, &key, &value);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_row_put(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    WT_ITEM key;
    WT_ITEM value;

    fileid = (uint32_t)(0);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(rand());
    key.data = NULL;
    key.size = 0;
    value.data = NULL;
    value.size = 0;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);

    fileid = (uint32_t)(rand());
    key.data = "data";
    key.size = 4;
    value.data = "data";
    value.size = 4;
    test_cmp_one__wt_logop_row_put(session, logrec_fmt, logrec_direct, fileid, &key, &value);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_row_remove(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    WT_ITEM key;

    fileid = (uint32_t)(0);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(1);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(rand());
    key.data = NULL;
    key.size = 0;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);

    fileid = (uint32_t)(rand());
    key.data = "data";
    key.size = 4;
    test_cmp_one__wt_logop_row_remove(session, logrec_fmt, logrec_direct, fileid, &key);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_row_truncate(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t fileid;
    WT_ITEM start;
    WT_ITEM stop;
    uint32_t mode;

    fileid = (uint32_t)(0);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(0);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(1);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(1);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(POS_1BYTE_MAX - 1);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(POS_1BYTE_MAX - 1);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(POS_1BYTE_MAX);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(POS_1BYTE_MAX);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(POS_1BYTE_MAX + 1);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(POS_1BYTE_MAX + 1);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(POS_2BYTE_MAX - 1);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(POS_2BYTE_MAX - 1);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(POS_2BYTE_MAX);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(POS_2BYTE_MAX);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(POS_2BYTE_MAX + 1);
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(POS_2BYTE_MAX + 1);
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(rand());
    start.data = NULL;
    start.size = 0;
    stop.data = NULL;
    stop.size = 0;
    mode = (uint32_t)(rand());
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);

    fileid = (uint32_t)(rand());
    start.data = "data";
    start.size = 4;
    stop.data = "data";
    stop.size = 4;
    mode = (uint32_t)(rand());
    test_cmp_one__wt_logop_row_truncate(
      session, logrec_fmt, logrec_direct, fileid, &start, &stop, mode);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_checkpoint_start(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);

    test_cmp_one__wt_logop_checkpoint_start(session, logrec_fmt, logrec_direct);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_prev_lsn(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    WT_LSN prev_lsn;

    prev_lsn.l.file = (uint32_t)(0);
    prev_lsn.l.offset = (uint32_t)(0);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(1);
    prev_lsn.l.offset = (uint32_t)(1);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(POS_1BYTE_MAX - 1);
    prev_lsn.l.offset = (uint32_t)(POS_1BYTE_MAX - 1);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(POS_1BYTE_MAX);
    prev_lsn.l.offset = (uint32_t)(POS_1BYTE_MAX);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(POS_1BYTE_MAX + 1);
    prev_lsn.l.offset = (uint32_t)(POS_1BYTE_MAX + 1);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(POS_2BYTE_MAX - 1);
    prev_lsn.l.offset = (uint32_t)(POS_2BYTE_MAX - 1);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(POS_2BYTE_MAX);
    prev_lsn.l.offset = (uint32_t)(POS_2BYTE_MAX);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(POS_2BYTE_MAX + 1);
    prev_lsn.l.offset = (uint32_t)(POS_2BYTE_MAX + 1);
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(rand());
    prev_lsn.l.offset = (uint32_t)(rand());
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);

    prev_lsn.l.file = (uint32_t)(rand());
    prev_lsn.l.offset = (uint32_t)(rand());
    test_cmp_one__wt_logop_prev_lsn(session, logrec_fmt, logrec_direct, &prev_lsn);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_backup_id(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint32_t index;
    uint64_t granularity;
    const char *id;

    index = (uint32_t)(0);
    granularity = (uint64_t)(0);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(1);
    granularity = (uint64_t)(1);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(POS_1BYTE_MAX - 1);
    granularity = (uint64_t)(POS_1BYTE_MAX - 1);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(POS_1BYTE_MAX);
    granularity = (uint64_t)(POS_1BYTE_MAX);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(POS_1BYTE_MAX + 1);
    granularity = (uint64_t)(POS_1BYTE_MAX + 1);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(POS_2BYTE_MAX - 1);
    granularity = (uint64_t)(POS_2BYTE_MAX - 1);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(POS_2BYTE_MAX);
    granularity = (uint64_t)(POS_2BYTE_MAX);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(POS_2BYTE_MAX + 1);
    granularity = (uint64_t)(POS_2BYTE_MAX + 1);
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(rand());
    granularity = (uint64_t)(rand());
    id = "";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);

    index = (uint32_t)(rand());
    granularity = (uint64_t)(rand());
    id = "string";
    test_cmp_one__wt_logop_backup_id(session, logrec_fmt, logrec_direct, index, granularity, id);
}

__attribute__((__unused__)) static void
test_cmp_all__wt_logop_txn_timestamp(
  WT_SESSION_IMPL *session, WT_ITEM *logrec_fmt, WT_ITEM *logrec_direct)
{
    uint64_t time_sec;
    uint64_t time_nsec;
    uint64_t commit_ts;
    uint64_t durable_ts;
    uint64_t first_commit_ts;
    uint64_t prepare_ts;
    uint64_t read_ts;

    time_sec = (uint64_t)(0);
    time_nsec = (uint64_t)(0);
    commit_ts = (uint64_t)(0);
    durable_ts = (uint64_t)(0);
    first_commit_ts = (uint64_t)(0);
    prepare_ts = (uint64_t)(0);
    read_ts = (uint64_t)(0);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(1);
    time_nsec = (uint64_t)(1);
    commit_ts = (uint64_t)(1);
    durable_ts = (uint64_t)(1);
    first_commit_ts = (uint64_t)(1);
    prepare_ts = (uint64_t)(1);
    read_ts = (uint64_t)(1);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(POS_1BYTE_MAX - 1);
    time_nsec = (uint64_t)(POS_1BYTE_MAX - 1);
    commit_ts = (uint64_t)(POS_1BYTE_MAX - 1);
    durable_ts = (uint64_t)(POS_1BYTE_MAX - 1);
    first_commit_ts = (uint64_t)(POS_1BYTE_MAX - 1);
    prepare_ts = (uint64_t)(POS_1BYTE_MAX - 1);
    read_ts = (uint64_t)(POS_1BYTE_MAX - 1);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(POS_1BYTE_MAX);
    time_nsec = (uint64_t)(POS_1BYTE_MAX);
    commit_ts = (uint64_t)(POS_1BYTE_MAX);
    durable_ts = (uint64_t)(POS_1BYTE_MAX);
    first_commit_ts = (uint64_t)(POS_1BYTE_MAX);
    prepare_ts = (uint64_t)(POS_1BYTE_MAX);
    read_ts = (uint64_t)(POS_1BYTE_MAX);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(POS_1BYTE_MAX + 1);
    time_nsec = (uint64_t)(POS_1BYTE_MAX + 1);
    commit_ts = (uint64_t)(POS_1BYTE_MAX + 1);
    durable_ts = (uint64_t)(POS_1BYTE_MAX + 1);
    first_commit_ts = (uint64_t)(POS_1BYTE_MAX + 1);
    prepare_ts = (uint64_t)(POS_1BYTE_MAX + 1);
    read_ts = (uint64_t)(POS_1BYTE_MAX + 1);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(POS_2BYTE_MAX - 1);
    time_nsec = (uint64_t)(POS_2BYTE_MAX - 1);
    commit_ts = (uint64_t)(POS_2BYTE_MAX - 1);
    durable_ts = (uint64_t)(POS_2BYTE_MAX - 1);
    first_commit_ts = (uint64_t)(POS_2BYTE_MAX - 1);
    prepare_ts = (uint64_t)(POS_2BYTE_MAX - 1);
    read_ts = (uint64_t)(POS_2BYTE_MAX - 1);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(POS_2BYTE_MAX);
    time_nsec = (uint64_t)(POS_2BYTE_MAX);
    commit_ts = (uint64_t)(POS_2BYTE_MAX);
    durable_ts = (uint64_t)(POS_2BYTE_MAX);
    first_commit_ts = (uint64_t)(POS_2BYTE_MAX);
    prepare_ts = (uint64_t)(POS_2BYTE_MAX);
    read_ts = (uint64_t)(POS_2BYTE_MAX);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(POS_2BYTE_MAX + 1);
    time_nsec = (uint64_t)(POS_2BYTE_MAX + 1);
    commit_ts = (uint64_t)(POS_2BYTE_MAX + 1);
    durable_ts = (uint64_t)(POS_2BYTE_MAX + 1);
    first_commit_ts = (uint64_t)(POS_2BYTE_MAX + 1);
    prepare_ts = (uint64_t)(POS_2BYTE_MAX + 1);
    read_ts = (uint64_t)(POS_2BYTE_MAX + 1);
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(rand());
    time_nsec = (uint64_t)(rand());
    commit_ts = (uint64_t)(rand());
    durable_ts = (uint64_t)(rand());
    first_commit_ts = (uint64_t)(rand());
    prepare_ts = (uint64_t)(rand());
    read_ts = (uint64_t)(rand());
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);

    time_sec = (uint64_t)(rand());
    time_nsec = (uint64_t)(rand());
    commit_ts = (uint64_t)(rand());
    durable_ts = (uint64_t)(rand());
    first_commit_ts = (uint64_t)(rand());
    prepare_ts = (uint64_t)(rand());
    read_ts = (uint64_t)(rand());
    test_cmp_one__wt_logop_txn_timestamp(session, logrec_fmt, logrec_direct, time_sec, time_nsec,
      commit_ts, durable_ts, first_commit_ts, prepare_ts, read_ts);
}

__attribute__((__unused__)) static void
test_cmp_all(WT_SESSION_IMPL *session)
{
    WT_ITEM logrec_fmt, logrec_direct;

    WT_CLEAR(logrec_fmt);
    assert(__wt_buf_init(session, &logrec_fmt, 0) == 0);
    WT_CLEAR(logrec_direct);
    assert(__wt_buf_init(session, &logrec_direct, 0) == 0);

    test_cmp_all__wt_logop_col_modify(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_col_put(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_col_remove(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_col_truncate(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_row_modify(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_row_put(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_row_remove(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_row_truncate(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_checkpoint_start(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_prev_lsn(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_backup_id(session, &logrec_fmt, &logrec_direct);
    test_cmp_all__wt_logop_txn_timestamp(session, &logrec_fmt, &logrec_direct);

    __wt_buf_free(session, &logrec_fmt);
    __wt_buf_free(session, &logrec_direct);
}
