Import('env_util')

env_util.Program('intpack-test', ['intpack-test.c'])
env_util.Program('intpack-test2', ['intpack-test2.c'])
env_util.Program('intpack-test3', ['intpack-test3.c'])
env_util.Program('packing-test', ['packing-test.c'])
