#!/usr/bin/env python3
#
# Suite mode manifests for test/suite/run.py.
#
# These lists are intentionally conservative and are expected to evolve over time.
#

from __future__ import annotations

# "plaid" mode: ultra-short local sample (target ~30s wall clock @ -j 24).
# This list was derived from per-scenario timing data and excludes modules with very slow
# individual scenarios in the sampled run.
PLAUD_TESTS: tuple[str, ...] = (
    "test_reconfig04",
    "test_timestamp25",
    "test_disagg02",
    "test_eviction05",
    "test_compact06",
    "test_eviction04",
    "test_txn17",
    "test_layered78",
    "test_prepare02",
    "test_prepare18",
    "test_reconfig05",
    "test_encrypt03",
    "test_stat14",
    "test_stat11",
    "test_txn30",
    "test_layered02",
    "test_scrub_eviction_prepare",
    "test_timestamp01",
    "test_hs29",
    "test_layered51",
    "test_prepare19",
    # Include util coverage (wt CLI + utility operations).
    "test_util01",
    "test_util02",
    "test_util03",
    "test_util04",
    "test_util07",
    "test_util08",
    "test_util09",
    "test_util11",
    "test_util12",
    "test_util13",
    "test_util14",
    "test_util15",
    "test_util17",
    "test_util18",
    "test_util19",
    "test_util21",
    "test_util22",
    "test_util23",
    "test_config13",
    "test_timestamp16",
    "test_cursor22",
    "test_strerror01",
    "test_readonly03",
    "test_layered01",
    "test_truncate26",
    "test_disagg01",
    "test_timestamp09",
    "test_cache_evict_config01",
    "test_layered33",
    "test_readonly02",
    "test_drop03",
    "test_version",
    "test_bug024",
    "test_unicode01",
    "test_bug020",
    "test_live_restore07",
    "test_metadata_cursor04",
    "test_layered03",
    "test_hs25",
    "test_layered67",
    "test_compact14",
    "test_layered16",
    "test_bug017",
    "test_txn21",
    "test_verify2",
    "test_layered40",
    "test_bug009",
    "test_debug_mode05",
    "test_turtle01",
    "test_prepare_hs05",
    "test_util23",
    "test_prepare_cursor02",
    "test_hs16",
    "test_index03",
    "test_cursor_bound20",
    "test_compact08",
    "test_drop01",
    "test_debug_info",
    "test_bug007",
    "test_reconcile02",
    "test_txn12",
    "test_stat_log02",
    "test_debug_mode10",
    "test_debug_mode01",
    "test_layered66",
    "test_baseconfig",
    "test_prepare14",
    "test_prepare26",
    "test_txn28",
    "test_update_obsolete_short_chain",
    "test_cursor04",
    "test_prefetch03",
    "test_compact15",
    "test_bug015",
    "test_timestamp23",
    "test_import10",
    "test_prepare_cursor01",
    "test_hs13",
    "test_cursor19",
    "test_txn_uncommitted",
    "test_dictionary03",
    "test_cursor23",
    "test_prepare06",
    "test_hs12",
    "test_layered53",
    "test_checkpoint_snapshot01",
    "test_layered46",
    "test_timestamp28",
    "test_cursor_bound13",
    "test_sweep02",
    "test_prepare03",
    "test_hs28",
    "test_debug_mode04",
    "test_dictionary02",
    "test_timestamp05",
    "test_dictionary04",
    "test_timestamp24",
    "test_debug_mode07",
    "test_layered50",
    "test_util04",
    "test_bug005",
    "test_prepare05",
    "test_assert07",
    "test_hs19",
    "test_layered88",
    "test_cursor15",
    "test_debug_mode06",
    "test_prepare27",
    "test_bug033",
    "test_timestamp17",
    "test_isolation01",
    "test_cursor_bound15",
    "test_debug_mode11",
    "test_metadata_cursor01",
    "test_rollback_to_stable44",
    "test_bug032",
    "test_layered58",
    "test_debug_mode03",
    "test_split",
    "test_cursor_bound16",
    "test_layered41",
    "test_stat13",
    "test_backup07",
    "test_backup16",
    "test_layered07",
    "test_empty_value",
    "test_prepare11",
    "test_prepare29",
    "test_bug006",
    # Heavier (still non-tiered) module to increase plaid runtime/coverage.
    "test_txn19",
)


def tests_for_mode(mode: str | None) -> tuple[str, ...] | None:
    if mode is None:
        return None
    m = mode.strip().lower()
    if m in ("plaid", "plain"):
        return PLAUD_TESTS
    return None

