[project]
name = "wt-mcp"
version = "0.1.0"
description = "MCP Server for WiredTiger development and debugging"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.0",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
]
