Import('*')
zstd_src = ([
    'zstd_compress.c'])

if GetOption("enable_static"):
    zstd = env.StaticLibrary(target="zstd", source=zstd_src)
else:   
    zstd = env.SharedLibrary(target="zstd", source=zstd_src)
