Import('*')
test_util_src = ([
    'misc.c',
    'parse_opts.c',
    'thread.c'])

if GetOption("enable_static"):
    test_util = env.StaticLibrary(target="test_util", source=test_util_src)
else:   
    test_util = env.SharedLibrary(target="test_util", source=test_util_src)
Default(test_util)

