#include "api_func_map.h"

const char *__WT_API_NAMES[] = {"WT_CURSOR::get_key", "WT_CURSOR::get_value",
  "WT_CURSOR::get_raw_key_value", "WT_CURSOR::set_key", "WT_CURSOR::set_value",
  "WT_CURSOR::compare", "WT_CURSOR::equals", "WT_CURSOR::next", "WT_CURSOR::prev",
  "WT_CURSOR::reset", "WT_CURSOR::search", "WT_CURSOR::search_near", "WT_CURSOR::insert",
  "WT_CURSOR::insert_check", "WT_CURSOR::modify", "WT_CURSOR::update", "WT_CURSOR::remove",
  "WT_CURSOR::reserve", "WT_CURSOR::checkpoint_id", "WT_CURSOR::close", "WT_CURSOR::largest_key",
  "WT_CURSOR::reconfigure", "WT_CURSOR::bound", "WT_CURSOR::cache", "WT_CURSOR::reopen",
  "WT_SESSION::close", "WT_SESSION::reconfigure", "WT_SESSION::strerror", "WT_SESSION::open_cursor",
  "WT_SESSION::alter", "WT_SESSION::bind_configuration", "WT_SESSION::create",
  "WT_SESSION::compact", "WT_SESSION::drop", "WT_SESSION::join", "WT_SESSION::log_flush",
  "WT_SESSION::log_printf", "WT_SESSION::reset", "WT_SESSION::salvage", "WT_SESSION::truncate",
  "WT_SESSION::upgrade", "WT_SESSION::verify", "WT_SESSION::begin_transaction",
  "WT_SESSION::commit_transaction", "WT_SESSION::prepare_transaction",
  "WT_SESSION::rollback_transaction", "WT_SESSION::query_timestamp",
  "WT_SESSION::timestamp_transaction", "WT_SESSION::timestamp_transaction_uint",
  "WT_SESSION::checkpoint", "WT_SESSION::reset_snapshot", "WT_SESSION::transaction_pinned_range",
  "WT_SESSION::get_rollback_reason", "WT_SESSION::breakpoint", "WT_CONNECTION::close",
  "WT_CONNECTION::debug_info", "WT_CONNECTION::reconfigure", "WT_CONNECTION::get_home",
  "WT_CONNECTION::compile_configuration", "WT_CONNECTION::configure_method",
  "WT_CONNECTION::is_new", "WT_CONNECTION::open_session", "WT_CONNECTION::query_timestamp",
  "WT_CONNECTION::set_timestamp", "WT_CONNECTION::rollback_to_stable",
  "WT_CONNECTION::load_extension", "WT_CONNECTION::add_data_source", "WT_CONNECTION::add_collator",
  "WT_CONNECTION::add_compressor", "WT_CONNECTION::add_encryptor", "WT_CONNECTION::add_extractor",
  "WT_CONNECTION::set_file_system", "WT_CONNECTION::add_storage_source",
  "WT_CONNECTION::get_storage_source", "WT_CONNECTION::get_extension_api"};
