/* DO NOT EDIT: automatically built by format/config.sh. */

#pragma once

#define C_TYPE_MATCH(cp, type) \
    (!F_ISSET(cp, C_TYPE_ROW) || ((type) == ROW && F_ISSET(cp, C_TYPE_ROW)))

typedef struct {
    const char *name; /* Configuration item */
    const char *desc; /* Configuration description */

#define C_BOOL 0x001u        /* Boolean (true if roll of 1-to-100 is <= CONFIG->min) */
#define C_IGNORE 0x002u      /* Not a simple randomization, configured specially */
#define C_POW2 0x004u        /* Value must be power of 2 */
#define C_STRING 0x008u      /* String (rather than integral) */
#define C_TABLE 0x010u       /* Value is per table, not global */
#define C_TYPE_ROW 0x040u    /* Value is only relevant to RS */
#define C_ZERO_NOTSET 0x100u /* Ignore zero values */
    uint32_t flags;

    uint32_t min;     /* Minimum value */
    uint32_t maxrand; /* Maximum value randomly chosen */
    uint32_t maxset;  /* Maximum value explicitly set */

    u_int off; /* Value offset */
} CONFIG;

#define V_MAX_TABLES_CONFIG WT_THOUSAND

#define V_GLOBAL_ASSERT_READ_TIMESTAMP 0
#define V_GLOBAL_BACKGROUND_COMPACT 1
#define V_GLOBAL_BACKGROUND_COMPACT_FREE_SPACE_TARGET 2
#define V_GLOBAL_BACKUP 3
#define V_GLOBAL_BACKUP_INCREMENTAL 4
#define V_GLOBAL_BACKUP_INCR_GRANULARITY 5
#define V_GLOBAL_BACKUP_LIVE_RESTORE 6
#define V_GLOBAL_BACKUP_LIVE_RESTORE_READ_SIZE 7
#define V_GLOBAL_BACKUP_LIVE_RESTORE_THREADS 8
#define V_GLOBAL_BLOCK_CACHE 9
#define V_GLOBAL_BLOCK_CACHE_CACHE_ON_CHECKPOINT 10
#define V_GLOBAL_BLOCK_CACHE_CACHE_ON_WRITES 11
#define V_GLOBAL_BLOCK_CACHE_SIZE 12
#define V_TABLE_BTREE_COMPRESSION 13
#define V_TABLE_BTREE_DICTIONARY 14
#define V_TABLE_BTREE_INTERNAL_KEY_TRUNCATION 15
#define V_TABLE_BTREE_INTERNAL_PAGE_MAX 16
#define V_TABLE_BTREE_KEY_MAX 17
#define V_TABLE_BTREE_KEY_MIN 18
#define V_TABLE_BTREE_LEAF_PAGE_MAX 19
#define V_TABLE_BTREE_MEMORY_PAGE_MAX 20
#define V_TABLE_BTREE_PREFIX_LEN 21
#define V_TABLE_BTREE_PREFIX_COMPRESSION 22
#define V_TABLE_BTREE_PREFIX_COMPRESSION_MIN 23
#define V_TABLE_BTREE_REPEAT_DATA_PCT 24
#define V_TABLE_BTREE_REVERSE 25
#define V_TABLE_BTREE_SPLIT_PCT 26
#define V_TABLE_BTREE_VALUE_MAX 27
#define V_TABLE_BTREE_VALUE_MIN 28
#define V_GLOBAL_CACHE 29
#define V_GLOBAL_CACHE_EVICT_MAX 30
#define V_GLOBAL_CACHE_EVICTION_DIRTY_TARGET 31
#define V_GLOBAL_CACHE_EVICTION_DIRTY_TRIGGER 32
#define V_GLOBAL_CACHE_MINIMUM 33
#define V_GLOBAL_CACHE_MAXIMUM 34
#define V_GLOBAL_CHECKPOINT 35
#define V_GLOBAL_CHECKPOINT_LOG_SIZE 36
#define V_GLOBAL_CHECKPOINT_WAIT 37
#define V_GLOBAL_CHUNK_CACHE 38
#define V_GLOBAL_CHUNK_CACHE_CAPACITY 39
#define V_GLOBAL_CHUNK_CACHE_CHUNK_SIZE 40
#define V_GLOBAL_CHUNK_CACHE_STORAGE_PATH 41
#define V_GLOBAL_CHUNK_CACHE_TYPE 42
#define V_GLOBAL_COMPACT_FREE_SPACE_TARGET 43
#define V_GLOBAL_DEBUG_BACKGROUND_COMPACT 44
#define V_GLOBAL_DEBUG_CHECKPOINT_RETENTION 45
#define V_GLOBAL_DEBUG_CURSOR_REPOSITION 46
#define V_GLOBAL_DEBUG_EVICTION 47
#define V_GLOBAL_DEBUG_LOG_RETENTION 48
#define V_GLOBAL_DEBUG_REALLOC_EXACT 49
#define V_GLOBAL_DEBUG_REALLOC_MALLOC 50
#define V_GLOBAL_DEBUG_SLOW_CHECKPOINT 51
#define V_GLOBAL_DEBUG_TABLE_LOGGING 52
#define V_GLOBAL_DEBUG_UPDATE_RESTORE_EVICT 53
#define V_TABLE_DISK_CHECKSUM 54
#define V_GLOBAL_DISK_DATA_EXTEND 55
#define V_GLOBAL_DISK_ENCRYPTION 56
#define V_TABLE_DISK_FIRSTFIT 57
#define V_GLOBAL_DISK_MMAP 58
#define V_GLOBAL_DISK_MMAP_ALL 59
#define V_GLOBAL_EVICTION_EVICT_USE_SOFTPTR 60
#define V_GLOBAL_FILE_MANAGER_CLOSE_HANDLE_MINIMUM 61
#define V_GLOBAL_FILE_MANAGER_CLOSE_IDLE_TIME 62
#define V_GLOBAL_FILE_MANAGER_CLOSE_SCAN_INTERVAL 63
#define V_GLOBAL_FORMAT_ABORT 64
#define V_GLOBAL_FORMAT_INDEPENDENT_THREAD_RNG 65
#define V_GLOBAL_FORMAT_MAJOR_TIMEOUT 66
#define V_GLOBAL_IMPORT 67
#define V_GLOBAL_LOGGING 68
#define V_GLOBAL_LOGGING_COMPRESSION 69
#define V_GLOBAL_LOGGING_FILE_MAX 70
#define V_GLOBAL_LOGGING_PREALLOC 71
#define V_GLOBAL_LOGGING_REMOVE 72
#define V_GLOBAL_OBSOLETE_CLEANUP_METHOD 73
#define V_GLOBAL_OBSOLETE_CLEANUP_WAIT 74
#define V_GLOBAL_OPS_ALTER 75
#define V_GLOBAL_OPS_COMPACTION 76
#define V_GLOBAL_OPS_HS_CURSOR 77
#define V_TABLE_OPS_PARETO 78
#define V_TABLE_OPS_PARETO_SKEW 79
#define V_TABLE_OPS_PCT_DELETE 80
#define V_TABLE_OPS_PCT_INSERT 81
#define V_TABLE_OPS_PCT_MODIFY 82
#define V_TABLE_OPS_PCT_READ 83
#define V_TABLE_OPS_PCT_WRITE 84
#define V_GLOBAL_OPS_BOUND_CURSOR 85
#define V_GLOBAL_OPS_PREPARE 86
#define V_GLOBAL_OPS_RANDOM_CURSOR 87
#define V_GLOBAL_OPS_SALVAGE 88
#define V_GLOBAL_OPS_THROTTLE 89
#define V_GLOBAL_OPS_THROTTLE_SLEEP_US 90
#define V_TABLE_OPS_TRUNCATE 91
#define V_GLOBAL_OPS_VERIFY 92
#define V_GLOBAL_PREFETCH 93
#define V_GLOBAL_QUIET 94
#define V_GLOBAL_RANDOM_DATA_SEED 95
#define V_GLOBAL_RANDOM_EXTRA_SEED 96
#define V_GLOBAL_RUNS_IN_MEMORY 97
#define V_TABLE_RUNS_MIRROR 98
#define V_GLOBAL_RUNS_OPS 99
#define V_GLOBAL_RUNS_PREDICTABLE_REPLAY 100
#define V_TABLE_RUNS_ROWS 101
#define V_TABLE_RUNS_SOURCE 102
#define V_GLOBAL_RUNS_TABLES 103
#define V_GLOBAL_RUNS_THREADS 104
#define V_GLOBAL_RUNS_TIMER 105
#define V_TABLE_RUNS_TYPE 106
#define V_GLOBAL_RUNS_VERIFY_FAILURE_DUMP 107
#define V_GLOBAL_STATISTICS_MODE 108
#define V_GLOBAL_STATISTICS_LOG_SOURCES 109
#define V_GLOBAL_STRESS_AGGRESSIVE_STASH_FREE 110
#define V_GLOBAL_STRESS_AGGRESSIVE_SWEEP 111
#define V_GLOBAL_STRESS_CHECKPOINT 112
#define V_GLOBAL_STRESS_CHECKPOINT_EVICT_PAGE 113
#define V_GLOBAL_STRESS_CHECKPOINT_PREPARE 114
#define V_GLOBAL_STRESS_COMPACT_SLOW 115
#define V_GLOBAL_STRESS_EVICT_REPOSITION 116
#define V_GLOBAL_STRESS_FAILPOINT_EVICTION_SPLIT 117
#define V_GLOBAL_STRESS_FAILPOINT_HS_DELETE_KEY_FROM_TS 118
#define V_GLOBAL_STRESS_HS_CHECKPOINT_DELAY 119
#define V_GLOBAL_STRESS_HS_SEARCH 120
#define V_GLOBAL_STRESS_HS_SWEEP 121
#define V_GLOBAL_STRESS_PREFETCH_DELAY 122
#define V_GLOBAL_STRESS_PREPARE_RESOLUTION_1 123
#define V_GLOBAL_STRESS_SLEEP_BEFORE_READ_OVERFLOW_ONPAGE 124
#define V_GLOBAL_STRESS_SPLIT_1 125
#define V_GLOBAL_STRESS_SPLIT_2 126
#define V_GLOBAL_STRESS_SPLIT_3 127
#define V_GLOBAL_STRESS_SPLIT_4 128
#define V_GLOBAL_STRESS_SPLIT_5 129
#define V_GLOBAL_STRESS_SPLIT_6 130
#define V_GLOBAL_STRESS_SPLIT_7 131
#define V_GLOBAL_STRESS_SPLIT_8 132
#define V_GLOBAL_TIERED_STORAGE_FLUSH_FREQUENCY 133
#define V_GLOBAL_TIERED_STORAGE_STORAGE_SOURCE 134
#define V_GLOBAL_TRANSACTION_IMPLICIT 135
#define V_GLOBAL_TRANSACTION_OPERATION_TIMEOUT_MS 136
#define V_GLOBAL_TRANSACTION_TIMESTAMPS 137
#define V_GLOBAL_WIREDTIGER_CONFIG 138
#define V_GLOBAL_WIREDTIGER_RWLOCK 139
#define V_GLOBAL_WIREDTIGER_LEAK_MEMORY 140

#define V_ELEMENT_COUNT 141
