/* DO NOT EDIT: automatically built by format/config.sh. */

#define C_TYPE_MATCH(cp, type)                                                                    \
    (!F_ISSET(cp, (C_TYPE_FIX | C_TYPE_ROW | C_TYPE_VAR)) ||                                      \
      ((type) == FIX && F_ISSET(cp, C_TYPE_FIX)) || ((type) == ROW && F_ISSET(cp, C_TYPE_ROW)) || \
      ((type) == VAR && F_ISSET(cp, C_TYPE_VAR)))

typedef struct {
    const char *name; /* Configuration item */
    const char *desc; /* Configuration description */

#define C_BOOL 0x001u     /* Boolean (true if roll of 1-to-100 is <= CONFIG->min) */
#define C_IGNORE 0x002u   /* Not a simple randomization, configured specially */
#define C_STRING 0x004u   /* String (rather than integral) */
#define C_TABLE 0x008u    /* Value is per table, not global */
#define C_TYPE_FIX 0x010u /* Value is only relevant to FLCS */
#define C_TYPE_LSM 0x020u /* Value is only relevant to LSM */
#define C_TYPE_ROW 0x040u /* Value is only relevant to RS */
#define C_TYPE_VAR 0x080u /* Value is only relevant to VLCS */
#define C_VERSION2 0x100u /* Ignore in version 2 configurations */
    uint32_t flags;

    uint32_t min;     /* Minimum value */
    uint32_t maxrand; /* Maximum value randomly chosen */
    uint32_t maxset;  /* Maximum value explicitly set */

    u_int off; /* Value offset */
} CONFIG;

#define V_MAX_TABLES_CONFIG 1000

#define V_GLOBAL_ASSERT_READ_TIMESTAMP 0
#define V_GLOBAL_ASSERT_WRITE_TIMESTAMP 1
#define V_GLOBAL_BACKUP 2
#define V_GLOBAL_BACKUP_INCREMENTAL 3
#define V_GLOBAL_BACKUP_INCR_GRANULARITY 4
#define V_TABLE_BTREE_BITCNT 5
#define V_TABLE_BTREE_COMPRESSION 6
#define V_TABLE_BTREE_DICTIONARY 7
#define V_TABLE_BTREE_HUFFMAN_VALUE 8
#define V_TABLE_BTREE_INTERNAL_KEY_TRUNCATION 9
#define V_TABLE_BTREE_INTERNAL_PAGE_MAX 10
#define V_TABLE_BTREE_KEY_MAX 11
#define V_TABLE_BTREE_KEY_MIN 12
#define V_TABLE_BTREE_LEAF_PAGE_MAX 13
#define V_TABLE_BTREE_MEMORY_PAGE_MAX 14
#define V_TABLE_BTREE_PREFIX 15
#define V_TABLE_BTREE_PREFIX_COMPRESSION 16
#define V_TABLE_BTREE_PREFIX_COMPRESSION_MIN 17
#define V_TABLE_BTREE_REPEAT_DATA_PCT 18
#define V_TABLE_BTREE_REVERSE 19
#define V_TABLE_BTREE_SPLIT_PCT 20
#define V_TABLE_BTREE_VALUE_MAX 21
#define V_TABLE_BTREE_VALUE_MIN 22
#define V_GLOBAL_CACHE 23
#define V_GLOBAL_CACHE_EVICT_MAX 24
#define V_GLOBAL_CACHE_MINIMUM 25
#define V_GLOBAL_CHECKPOINT 26
#define V_GLOBAL_CHECKPOINT_LOG_SIZE 27
#define V_GLOBAL_CHECKPOINT_WAIT 28
#define V_TABLE_DISK_CHECKSUM 29
#define V_GLOBAL_DISK_DATA_EXTEND 30
#define V_GLOBAL_DISK_DIRECT_IO 31
#define V_GLOBAL_DISK_ENCRYPTION 32
#define V_TABLE_DISK_FIRSTFIT 33
#define V_GLOBAL_DISK_MMAP 34
#define V_GLOBAL_DISK_MMAP_ALL 35
#define V_GLOBAL_FORMAT_ABORT 36
#define V_GLOBAL_FORMAT_INDEPENDENT_THREAD_RNG 37
#define V_GLOBAL_FORMAT_MAJOR_TIMEOUT 38
#define V_GLOBAL_IMPORT 39
#define V_GLOBAL_LOGGING 40
#define V_GLOBAL_LOGGING_ARCHIVE 41
#define V_GLOBAL_LOGGING_COMPRESSION 42
#define V_GLOBAL_LOGGING_FILE_MAX 43
#define V_GLOBAL_LOGGING_PREALLOC 44
#define V_TABLE_LSM_AUTO_THROTTLE 45
#define V_TABLE_LSM_BLOOM 46
#define V_TABLE_LSM_BLOOM_BIT_COUNT 47
#define V_TABLE_LSM_BLOOM_HASH_COUNT 48
#define V_TABLE_LSM_BLOOM_OLDEST 49
#define V_TABLE_LSM_CHUNK_SIZE 50
#define V_TABLE_LSM_MERGE_MAX 51
#define V_GLOBAL_LSM_WORKER_THREADS 52
#define V_GLOBAL_OPS_ALTER 53
#define V_GLOBAL_OPS_COMPACTION 54
#define V_GLOBAL_OPS_HS_CURSOR 55
#define V_TABLE_OPS_PCT_DELETE 56
#define V_TABLE_OPS_PCT_INSERT 57
#define V_TABLE_OPS_PCT_MODIFY 58
#define V_TABLE_OPS_PCT_READ 59
#define V_TABLE_OPS_PCT_WRITE 60
#define V_GLOBAL_OPS_PREPARE 61
#define V_GLOBAL_OPS_RANDOM_CURSOR 62
#define V_GLOBAL_OPS_SALVAGE 63
#define V_TABLE_OPS_TRUNCATE 64
#define V_GLOBAL_OPS_VERIFY 65
#define V_GLOBAL_QUIET 66
#define V_GLOBAL_RUNS_IN_MEMORY 67
#define V_GLOBAL_RUNS_OPS 68
#define V_TABLE_RUNS_ROWS 69
#define V_TABLE_RUNS_SOURCE 70
#define V_GLOBAL_RUNS_TABLES 71
#define V_GLOBAL_RUNS_THREADS 72
#define V_GLOBAL_RUNS_TIMER 73
#define V_TABLE_RUNS_TYPE 74
#define V_GLOBAL_RUNS_VERIFY_FAILURE_DUMP 75
#define V_GLOBAL_STATISTICS 76
#define V_GLOBAL_STATISTICS_SERVER 77
#define V_GLOBAL_STRESS_AGGRESSIVE_SWEEP 78
#define V_GLOBAL_STRESS_CHECKPOINT 79
#define V_GLOBAL_STRESS_CHECKPOINT_RESERVED_TXNID_DELAY 80
#define V_GLOBAL_STRESS_CHECKPOINT_PREPARE 81
#define V_GLOBAL_STRESS_FAILPOINT_HS_DELETE_KEY_FROM_TS 82
#define V_GLOBAL_STRESS_FAILPOINT_HS_INSERT_1 83
#define V_GLOBAL_STRESS_FAILPOINT_HS_INSERT_2 84
#define V_GLOBAL_STRESS_HS_CHECKPOINT_DELAY 85
#define V_GLOBAL_STRESS_HS_SEARCH 86
#define V_GLOBAL_STRESS_HS_SWEEP 87
#define V_GLOBAL_STRESS_SPLIT_1 88
#define V_GLOBAL_STRESS_SPLIT_2 89
#define V_GLOBAL_STRESS_SPLIT_3 90
#define V_GLOBAL_STRESS_SPLIT_4 91
#define V_GLOBAL_STRESS_SPLIT_5 92
#define V_GLOBAL_STRESS_SPLIT_6 93
#define V_GLOBAL_STRESS_SPLIT_7 94
#define V_GLOBAL_TRANSACTION_IMPLICIT 95
#define V_GLOBAL_TRANSACTION_TIMESTAMPS 96
#define V_GLOBAL_WIREDTIGER_CONFIG 97
#define V_GLOBAL_WIREDTIGER_RWLOCK 98
#define V_GLOBAL_WIREDTIGER_LEAK_MEMORY 99

#define V_ELEMENT_COUNT 100
