Import('env_util')

Default(env_util.Program('t', [
    'alter.c',
    'backup.c',
    'bulk.c',
    'checkpoint.c',
    'compact.c',
    'config.c',
    'config_compat.c',
    'hs.c',
    'kv.c',
    'ops.c',
    'random.c',
    'rebalance.c',
    'salvage.c',
    'snap.c',
    't.c',
    'trace.c',
    'util.c',
    'wts.c']))
