/* This is an auto generated file, do not touch! */
#pragma once
#define WT_API_WT_CURSOR_get_key 0
#define WT_API_WT_CURSOR_get_value 1
#define WT_API_WT_CURSOR_get_raw_key_value 2
#define WT_API_WT_CURSOR_set_key 3
#define WT_API_WT_CURSOR_set_value 4
#define WT_API_WT_CURSOR_compare 5
#define WT_API_WT_CURSOR_equals 6
#define WT_API_WT_CURSOR_next 7
#define WT_API_WT_CURSOR_prev 8
#define WT_API_WT_CURSOR_reset 9
#define WT_API_WT_CURSOR_search 10
#define WT_API_WT_CURSOR_search_near 11
#define WT_API_WT_CURSOR_insert 12
#define WT_API_WT_CURSOR_insert_check 13
#define WT_API_WT_CURSOR_modify 14
#define WT_API_WT_CURSOR_update 15
#define WT_API_WT_CURSOR_remove 16
#define WT_API_WT_CURSOR_reserve 17
#define WT_API_WT_CURSOR_checkpoint_id 18
#define WT_API_WT_CURSOR_close 19
#define WT_API_WT_CURSOR_largest_key 20
#define WT_API_WT_CURSOR_reconfigure 21
#define WT_API_WT_CURSOR_bound 22
#define WT_API_WT_CURSOR_cache 23
#define WT_API_WT_CURSOR_reopen 24
#define WT_API_WT_SESSION_close 25
#define WT_API_WT_SESSION_reconfigure 26
#define WT_API_WT_SESSION_strerror 27
#define WT_API_WT_SESSION_open_cursor 28
#define WT_API_WT_SESSION_alter 29
#define WT_API_WT_SESSION_bind_configuration 30
#define WT_API_WT_SESSION_create 31
#define WT_API_WT_SESSION_compact 32
#define WT_API_WT_SESSION_drop 33
#define WT_API_WT_SESSION_join 34
#define WT_API_WT_SESSION_log_flush 35
#define WT_API_WT_SESSION_log_printf 36
#define WT_API_WT_SESSION_reset 37
#define WT_API_WT_SESSION_salvage 38
#define WT_API_WT_SESSION_truncate 39
#define WT_API_WT_SESSION_upgrade 40
#define WT_API_WT_SESSION_verify 41
#define WT_API_WT_SESSION_begin_transaction 42
#define WT_API_WT_SESSION_commit_transaction 43
#define WT_API_WT_SESSION_prepare_transaction 44
#define WT_API_WT_SESSION_rollback_transaction 45
#define WT_API_WT_SESSION_query_timestamp 46
#define WT_API_WT_SESSION_timestamp_transaction 47
#define WT_API_WT_SESSION_timestamp_transaction_uint 48
#define WT_API_WT_SESSION_checkpoint 49
#define WT_API_WT_SESSION_reset_snapshot 50
#define WT_API_WT_SESSION_transaction_pinned_range 51
#define WT_API_WT_SESSION_get_rollback_reason 52
#define WT_API_WT_SESSION_breakpoint 53
#define WT_API_WT_CONNECTION_close 54
#define WT_API_WT_CONNECTION_debug_info 55
#define WT_API_WT_CONNECTION_reconfigure 56
#define WT_API_WT_CONNECTION_get_home 57
#define WT_API_WT_CONNECTION_compile_configuration 58
#define WT_API_WT_CONNECTION_configure_method 59
#define WT_API_WT_CONNECTION_is_new 60
#define WT_API_WT_CONNECTION_open_session 61
#define WT_API_WT_CONNECTION_query_timestamp 62
#define WT_API_WT_CONNECTION_set_timestamp 63
#define WT_API_WT_CONNECTION_rollback_to_stable 64
#define WT_API_WT_CONNECTION_load_extension 65
#define WT_API_WT_CONNECTION_add_data_source 66
#define WT_API_WT_CONNECTION_add_collator 67
#define WT_API_WT_CONNECTION_add_compressor 68
#define WT_API_WT_CONNECTION_add_encryptor 69
#define WT_API_WT_CONNECTION_add_extractor 70
#define WT_API_WT_CONNECTION_set_file_system 71
#define WT_API_WT_CONNECTION_add_storage_source 72
#define WT_API_WT_CONNECTION_get_storage_source 73
#define WT_API_WT_CONNECTION_get_extension_api 74
#define WT_API_COUNT 75
extern const char* WT_API_NAMES[];
