name: PR Checklist

on:
  pull_request:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const comment = `
            Thanks for creating a pull request! Please answer the questions below by editing this comment.

            ## Type of change made in this PR
            - [ ] Functional change
            - [ ] Test-only change
            - [ ] Refactor-only change
            - [ ] Other non-functional change

            ## What makes this change safe?
            Answering this question helps the reviewers understand where they should focus their attention. Please consider these prompts:
            - How risky is this change? Why?
            - What tests are you adding, changing or relying on? Why?
            - What, if anything, are you concerned about that you'd like the reviewer to focus on?

            References:
            - [Risk level guide](https://github.com/wiredtiger/wiredtiger/blob/develop/.github/risk_level_guide.md)
            - [Testing frameworks](https://github.com/wiredtiger/wiredtiger/blob/develop/test/testing_frameworks.md)

            ## Checklist before requesting a review
            - [ ] I have performed a self-review of my code.
            - [ ] I have made corresponding changes to the documentation, or no documentation change is needed.
            - [ ] I have tests that show my change is correct, or have described above why functional test changes are not required.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
